#!/usr/bin/env node

const chalk = require('chalk')
const program = require('commander')
const { existsSync } = require('fs')
const { join } = require('path')
const { ncp } = require('ncp')

const DEFAULT_SOURCE_DIR = './_src'

let templateDirPath = './node_modules/static-generator/template'

if (!existsSync(templateDirPath)) {
  templateDirPath = 'template'
}

program
  .option(
    '-s, --source_dir <path>',
    `path to source folder, defaults to "${DEFAULT_SOURCE_DIR}"`,
    DEFAULT_SOURCE_DIR
  )
  .parse(process.argv)

const srcDir = program.source_dir

console.log(chalk.bold('create new folder for static page sources'))
console.log(`source_dir=${chalk.blue(srcDir)}`)
console.log('')

if (existsSync(srcDir)) {
  console.error(chalk.red('Error: source folder already exists.'))
  process.exit(1)
}

// Copy templates folder to output directory
ncp(templateDirPath, srcDir, err => {
  if (err) {
    console.error(chalk.red(err))
    console.log('')
    console.error(chalk.red('An error occurred!'))
    process.exit(1)
  } else {
    console.log(chalk.blue('( ͡° ͜ʖ ͡°) done!'))
  }
})
